#!/bin/zsh

su ianepperson

# Enable pyenv to function
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

caffeinate -s poetry run python main.py
